/**
 * dsh-artifacts vault exporter.
 *
 * Turn a folder of Markdown notes (an Obsidian vault, VS Code notes, blog
 * drafts, docs) into a static, self-contained HTML site: one page per note
 * plus a linked index. No frontmatter dialect is assumed beyond the common
 * "first `# heading` is the title" convention.
 *
 * @module dsh-artifacts/vault
 */

import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { renderArtifact, type RenderOptions } from './render.js'

export interface Note {
  /** Relative POSIX path to the source Markdown file. */
  path: string
  title: string
  excerpt: string
  markdown: string
}

export interface VaultOptions extends RenderOptions {
  /** Optional index title (defaults to the output title or "Notes"). */
  indexTitle?: string
}

export const SKIP_DIRS = new Set(['node_modules', '.git', '.obsidian', '.trash', '.DS_Store', 'dist', 'out'])

const MARKDOWN_EXT = /\.(md|markdown)$/i

function toPosix(path: string): string {
  return path.split(sep).join('/')
}

/** Extract a title from the first `# heading`, else the filename. */
export function noteTitle(markdown: string, filename: string): string {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n')
  for (const line of lines) {
    const match = /^#{1,6}\s+(.+)$/.exec(line.trim())
    if (match !== null && match[1] !== undefined && match[1].trim() !== '') {
      return match[1].trim()
    }
    // Stop scanning once we hit actual content without a heading.
    if (line.trim() !== '' && !line.trim().startsWith('<!--') && !line.trim().startsWith('---')) break
  }
  return filename.replace(MARKDOWN_EXT, '').replaceAll('-', ' ').replaceAll('_', ' ').trim()
}

/** First meaningful non-heading line, lightly cleaned, used as a card excerpt. */
export function noteExcerpt(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, '\n').split('\n')
  let inFence = false
  for (const raw of lines) {
    const line = raw.trim()
    if (/^```/.test(line)) {
      inFence = !inFence
      continue
    }
    if (inFence) continue
    if (line === '' || line.startsWith('#') || line.startsWith('<!--') || line.startsWith('---') || line.startsWith('> ')) continue
    const cleaned = line
      .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
      .replace(/[*_`~#>]/g, '')
      .trim()
    if (cleaned !== '') return cleaned.length > 180 ? `${cleaned.slice(0, 180)}...` : cleaned
  }
  return ''
}

/** Recursively collect Markdown files under `root`. */
export function collectNotes(root: string, options: { recursive?: boolean; maxBytes?: number } = {}): Note[] {
  const recursive = options.recursive ?? true
  const maxBytes = options.maxBytes ?? 2 * 1024 * 1024
  const out: Note[] = []

  const walk = (dir: string, depth: number): void => {
    if (!recursive && depth > 0) return
    let entries: string[] = []
    try {
      entries = readdirSync(dir)
    } catch {
      return
    }
    entries.sort()
    for (const entry of entries) {
      if (SKIP_DIRS.has(entry)) continue
      const full = join(dir, entry)
      let stat
      try {
        stat = statSync(full)
      } catch {
        continue
      }
      if (stat.isDirectory()) {
        walk(full, depth + 1)
        continue
      }
      if (!MARKDOWN_EXT.test(entry)) continue
      if (stat.size > maxBytes) continue
      let markdown: string
      try {
        markdown = readFileSync(full, 'utf8')
      } catch {
        continue
      }
      const rel = toPosix(relative(root, full))
      out.push({
        path: rel,
        title: noteTitle(markdown, entry),
        excerpt: noteExcerpt(markdown),
        markdown,
      })
    }
  }

  walk(root, 0)
  return out.sort((a, b) => a.path.localeCompare(b.path))
}

function noteHtmlPath(note: Note): string {
  return note.path.replace(MARKDOWN_EXT, '') + '.html'
}

function collapseInline(value: string): string {
  return value.replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').trim()
}

function linkLabel(value: string): string {
  return value.replaceAll('[', '(').replaceAll(']', ')')
}

/**
 * Render one page per note plus a linked `index.html`. Returns a map of
 * POSIX relative output paths to complete HTML documents.
 */
export function renderVault(notes: Note[], options: VaultOptions = {}): Record<string, string> {
  const theme = options.theme ?? 'paper'
  const footer = options.footer ?? 'generated by dsh-artifacts vault'
  const indexTitle = options.indexTitle ?? options.title ?? 'Notes'
  const files: Record<string, string> = {}

  for (const note of notes) {
    files[noteHtmlPath(note)] = renderArtifact({
      title: note.title,
      markdown: note.markdown,
      template: 'doc',
      theme,
      footer,
      lang: options.lang,
    }).html
  }

  const items: string[] = []
  for (const note of notes) {
    const suffix = note.excerpt !== '' ? ` — ${collapseInline(note.excerpt)}` : ''
    items.push(`- [${linkLabel(note.title)}](${noteHtmlPath(note)})${suffix}`)
  }
  const indexMarkdown = notes.length === 0
    ? '# Notes\n\n_No Markdown files found in this folder._'
    : `# ${indexTitle}\n\n${items.join('\n')}`

  files['index.html'] = renderArtifact({
    title: indexTitle,
    markdown: indexMarkdown,
    template: 'doc',
    theme,
    footer,
    lang: options.lang,
  }).html

  return files
}
